// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// capturedWriteOGR
CharacterVector capturedWriteOGR(SEXP obj, int obj_size, SEXP layer, Function writeOGR);
RcppExport SEXP geojsonio_capturedWriteOGR(SEXP objSEXP, SEXP obj_sizeSEXP, SEXP layerSEXP, SEXP writeOGRSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type obj_size(obj_sizeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type layer(layerSEXP);
    Rcpp::traits::input_parameter< Function >::type writeOGR(writeOGRSEXP);
    __result = Rcpp::wrap(capturedWriteOGR(obj, obj_size, layer, writeOGR));
    return __result;
END_RCPP
}
