# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' An \code{writeOGR} shim to capture stdout
#'
#' @param obj the \code{Spatial} object to use
#' @param obj_size pls pass in \code{object.size(obj)}
#' @param layer spatial layer to use
#' @param writeOGR pls pass in \code{writeOGR} (no quotes)
#' @param layer_options pls pass in layer options
#' @return character vector of GeoJSON if all goes well
#' @examples \dontrun{
#' capturedWriteOGR(cities[1:10,],
#'                  object.size(cities[1:10,]),
#'                  "cities",
#'                  writeOGR))
#' }
capturedWriteOGR <- function(obj, obj_size, layer, writeOGR, layer_options) {
    .Call('geojsonio_capturedWriteOGR', PACKAGE = 'geojsonio', obj, obj_size, layer, writeOGR, layer_options)
}

